### ISSUE TITLE
Detect and report out-of-date raft config on startup

### ISSUE THREAD

**Issue by bobg** [chain/chain#1167]
When starting cored, if the raft config is stale, you are likely to encounter a segfault in `Generator.makeBlock`. The non-obvious remedy is to remove the raft config (in `$HOME/.chaincore`) and restart.

Chain Core should detect this situation and report it to the user.

**Comment by kr** [comment]
This should never happen for an end user. We need to make sure there's no such thing as a "stale" raft config -- if we change the schema, we need to migrate the data just like for any other database.

Do you have a stack trace or other error from when this happened? If it's a bug that could affect someone who's not hacking on cored itself, I would like to track it down.

**Comment by tessr** [comment]
@danrobinson ran into it this morning, but I'm not sure exactly what he did to get there.

**Comment by bobg** [comment]
I've encountered it too. I'm guessing it has something to do with changes to the format of files on disk?

The stack trace looks like:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x157b81c]

goroutine 132 [running]:
chain/protocol.(*Chain).GenerateBlock(0xc4203780c0, 0x23b3340, 0xc4204342c0, 0x0, 0x0, 0xed09d5670, 0x397f00e1, 0x23f9ac0, 0x0, 0x0, ...)
    /Users/danielrobinson/Projects/go/src/chain/protocol/block.go:57 +0x7c
chain/core/generator.(*Generator).makeBlock(0xc420181320, 0x23b3340, 0xc4204342c0, 0x0, 0x0)
    /Users/danielrobinson/Projects/go/src/chain/core/generator/block.go:73 +0x4a9
chain/core/generator.(*Generator).Generate(0xc420181320, 0x23b3340, 0xc4204342c0, 0x3b9aca00, 0xc420400740)
    /Users/danielrobinson/Projects/go/src/chain/core/generator/generator.go:96 +0x12f
created by chain/core.(*API).lead
    /Users/danielrobinson/Projects/go/src/chain/core/run.go:284 +0x2e9
```

**Comment by kr** [comment]
Line 57 in block.go is

```
if timestampMS < prev.TimestampMS {
```

So presumably prev is nil.

**Comment by danrobinson** [comment]
It happened when I updated Chain Core to @erykwalder's most recent commit on the `ivy` branch from the previous one, reinstalled (`go install -tags "loopback_auth plain_http" ./cmd/...`), and deleted and recreated the database, but didn't destroy `.chaincore`.

**Comment by kr** [comment]
> deleted and recreated the database, but didn't destroy `.chaincore`

Okay, I think that might explain it. The core thinks it's still configured but doesn't have any blocks, and tries to generate a new block.

**Comment by kr** [comment]
I guess this is something anyone could run into, if they accidentally deleted their postgres db, or even just used the wrong db URL when starting cored one time. So to come back to @bobg's original point, we should detect when the raft state appears to be inconsistent with the pg state and shut down with a helpful message rather than crashing.

**Comment by jbowens** [comment]
How should we detect this? We could store the core ID in a postgresql table and error if it doesn't match the sinkdb config's core ID?

**Comment by kr** [comment]
> We could store the core ID in a postgresql table and error if it doesn't match the sinkdb config's core ID?

Yeah, something like that. But I'm not sure the core ID would work. What if the core's not configured or gets reset? We might need to generate a lower-level ID that lives outside the core config. Like a "raft cluster ID" or something.

**Comment by jbowens** [comment]
I ran into a couple wrinkles:
* I don't think we can detect the scenario where the raft storage directory is deleted but Postgres is not, because that's identical to the scenario of booting up a fresh cored process to be connected to an existing cluster. We could detect it if we only care about Developer Edition, I suppose.
* Existing version 1.2 Chain Cores will need to have their cluster IDs set. I was hoping that we could set the cluster ID in the /init-cluster endpoint only, but it seems like cmd/cored/main.go will need to set it if the Core is initialized and has no cluster ID.

**Comment by tessr** [comment]
> I don't think we can detect the scenario where the raft storage directory is deleted but Postgres is not, because that's identical to the scenario of booting up a fresh cored process to be connected to an existing cluster. 

I think this is okay. This isn't the scenario that causes the panic. What's more common is when the pg db disappears, but the raft directory is still around. 

What if we just store the coreID in raft and postgres, and check them both on startup? 

If they're the same: 👍 
If they're different: 💀 
If Postgres has one but raft doesn't: migrate 🦆 
If raft has one but Postgres doesn't: tell the user to delete their raft directory

**Comment by kr** [comment]
> just store the coreID in raft and postgres

Would this handle the case where pg disappears, and the raft directory is still around, but they haven't configured the core yet?

**Comment by tessr** [comment]
I think that's the last case?

**Comment by kr** [comment]
I thought we allocate the core ID when the core is configured. If the core hasn't been configured, would raft have a core ID?

**Comment by jbowens** [comment]
I think raft/sinkdb can be:
* uninitialized
* initialized but lacking a Core ID/Cluster ID/whatever we use
* initialized with a Core ID/Cluster ID/etc

If it's uninitialized, there's three possibilities:
1. It's a new cored process that might be added to an existing Chain Core cluster.
2. It's a 1.1.x Chain Core that needs to be migrated to using raft/sinkdb.
3. It's a cored process that lost its raft directory.

I'm not really sure how you distinguish these cases. In all three cases it's all possible for the Postgres database to have a record of the cluster ID.

**Comment by jbowens** [comment]
Ah sorry, I think I misread. We care about postgres disappearing, not the raft directory?

**Comment by kr** [comment]
Case 3 is actually equivalent to case 1. For case 2, don't we also keep track of migration status in postgres (by deleting the config)? Maybe we should make that migration status more explicit.

Like @tessr mentioned, a bigger problem is when postgres is missing (either because the db url is misconfigured or because it was dropped and raft wasn't).

**Comment by kr** [comment]
> We care about postgres disappearing, not the raft directory?

Ah, yeah, that's the case people have been running into.

**Comment by tessr** [comment]
@kr yes, you're right [about the coreid being set on config--a lot has happened in this thread since I started writing this comment]. 

In that particular case, though, we actually already get not-terrible errors. If I delete the pg database for an unconfigured core, create a new database and start the core again (without deleting the raft directory), I get:

```
RPC error: CH164 Already connected to a cluster
```

which is a) not a panic and b) a pretty good hint about what needs to happen. 

In general, I'm not sure that we will have a solution that catches all the cases. Obviously, if we can do something cleanly, let's do it, but I am okay with doing something relatively simple that will catch the most egregious case--when someone deletes and recreates their pg db _on a configured core_ which leads to a mysterious-looking panic in `GenerateBlock`. 

(Or, at least, using that solution as a starting point.)

**Comment by jbowens** [comment]
> Case 3 is actually equivalent to case 1.

It's almost equivalent except that you do have an orphaned raft node used for calculating quorum.
