### ISSUE TITLE
Set Production build to true

### ISSUE THREAD

**Issue by bsbits** [chain/chain#1176]
Buy default, when I run chain docker, the production build is set to false

`Production build:	false`

How do I change this to true ? and what is the difference between them ?

**Comment by kr** [comment]
Hey @bsbits, all builds of Chain Core Developer Edition are designed for development. They have features, such as the mock HSM and the data reset button, that are unsafe for use in production.

If you’re interested in rebuilding cored in a production configuration, and you don’t mind jumping in to the source code, you can see the existing Go build tags in the files in cmd/cored:

```
$ grep +build *.go
exec_unix.go://+build linux darwin
http_ok.go://+build http_ok
localhost_auth.go://+build localhost_auth
mockhsm.go://+build !no_mockhsm
no_mockhsm.go://+build no_mockhsm
race.go://+build race
reset.go://+build !no_reset
```

Just be aware that if you go this route, you’re mostly on your own. You can probably get help from the community on our [community Slack](https://slack.chain.com/).

If you need an officially supported production build, check out [Chain Core Enterprise Edition](https://chain.com/enterprise/).

I hope this helps!

**Comment by bsbits** [comment]
why are they unsafe for production ? If I remember well, dominic told me I can use for open source projects and I really thought I would build something with the Dev Edition.

Can't afford to pay for an Enterprise edition.

**Comment by kr** [comment]
Sure! You can absolutely use this for open source projects. In that case, I highly recommend recompiling in a configuration suitable for production.

- The mock HSM stores private keys in postgres in cleartext. It is an extra feature designed to make working with Chain Core much easier in development, but it shouldn't be used in production. It's not audited for security and its basic architecture is designed around convenience, not safety.
- The reset button deletes all your data! This comes in handy when you're iterating on a prototype, but is definitely something you never want to do in production.
- Developer edition allows unencrypted (non-TLS) "plain-HTTP" requests, but making unencrypted connections in production will leak sensitive data.
- Developer edition allows connections from localhost to access all RPCs without presenting any auth credentials. Again, this is super convenient in development because it means there's no setup to do after Chain Core is installed, but it's insecure for production use.

The safe option for all of these features is to turn them off completely in production.

**Comment by bsbits** [comment]
Oh, that is not good at all, if I want to use the Entreprise Edition, who to reach out at chain ?

**Comment by kr** [comment]
There's a contact form on https://chain.com/enterprise/.

**Comment by kr** [comment]
> And I assume there is NO way to migrate from Dev Edition to Enterprise ?

Developer Edition and Enterprise Edition are compatible; migrating is easy.

**Comment by bsbits** [comment]
Amazing, you guys rock.
