### ISSUE TITLE
Add decimal support to the amount field

### ISSUE THREAD

**Issue by fcanevar** [chain/chain#215]
Although there are workarounds, it would be very helpful to have decimal support to the amount field in transactions. For example, if my asset is a currency (USD, EUR, etc) it would be easier to work with floating point numbers that to use strictly integer numbers.

**Comment by kr** [comment]
Hi @fcanevar, thank you for the suggestion! Yeah I agree it would be nice to be able to say `5.25` dollars instead of `525` cents. Unfortunately, floating point numbers have some tricky corner cases that make them dangerous to use for monetary values, most notably that there are some integers that cannot be represented at all in floating point. For this reason, all existing financial database systems use exact integer datatypes or exact decimal datatypes for money, and Chain Core is no exception.

It would be possible for us to provide some SDK convenience functions to map exact decimal values to and from the underlying integer amounts. (Java might have an exact decimal datatype in its standard library, but I'm not sure about the other languages on our roadmap.) We haven't seen much demand for fractional amounts so far (this is the first request I'm aware of) but we will certainly keep it in our trello.

For now, I'm afraid I'll have to ask you to keep using the workaround of expressing everything in cents (or the equivalent indivisible unit for whatever asset you're working with).

**Comment by fcanevar** [comment]
Hi @kr , thanks for the reply, now I understand the technical issues behind this choice.
Regards, Fabio

**Comment by oleganza** [comment]
I think the good compromise is having a standard (but not blockchain-consensus-critical) asset definition format that describes formatting details such as divisibility, asset category (points, currency, miles, stocks, etc), currency code, ticker etc. So the SDK could provide application with two additional representations of the raw `amount`: `decimalAmount` and `formattedAmount` (both in forms of setters and getters).
