### ISSUE TITLE
sdk/java: review exception usage

### ISSUE THREAD

**Issue by fcanevar** [chain/chain#231]
#### Environment 
1. latest
2. Java latest from git
3. any

Most of the exception used in the java SDK are masked by ChainException, it would be a better solution to expose some of the exception "flavors" so that different situations are manageable differently.

E.g.: Transaction.Builder.build throws ChainException, but it's just a mask for: JsonParseException, BadURLException, JSONException, HTTPException, ConnectivityException, APIException.

I'd suggest to delete ChainException and to use proper exception handling.

Code to review:
- Transaction.Build.build(Client)
- BatchResponse.BatchResponse(Response, Gson, Type, Type)
- Client (various methods)

**Comment by jeffomatic** [comment]
@fcanevar Can you clarify what you mean by "masking"? `ChainException` intended to separate exception cases known to the SDK from those that aren't, and you can still catch the subtypes (`APIException`, etc.) in application code using a `catch` statement for a given subtype or group of subtypes. For example, this works:

```
try {
  Transaction.Template t = new Transaction.Builder()
    .addAction(...)
    .build(client);
} catch (APIException e) {
  ...
}
```

Any SDK method that make calls to the API could potentially throw a number of exception types that you mentioned, since there are many ways an API call could fail.

Perhaps the problem is that the `throws` clauses in the method signatures are not granular enough as documentation/hints to the developer?

**Comment by fcanevar** [comment]
@jeffomatic Thanks for the reply, you're right on the money. Having more granular throws would be helpful.

**Comment by jeffomatic** [comment]
@fcanevar Just to clarify: the issue is that when you are using the SDK in an IDE, or reading its source code, it's difficult for you to tell what exceptions might be thrown?

**Comment by fcanevar** [comment]
@jeffomatic Yes, not only it's difficult to read and it doesn't "speak for itself", but just take for example Transaction.Builder.build(Client) : throws a ChainException   and the method that is called inside throws ChainException itself so it's not granular enough and it's almost impossible to understand what kind of exceptions are thrown. It took me almost 30minutes to look through the code and understand that there are at least 6 possible exceptions for that single piece of code. The Idea of having all Exceptions from chain under a "ChainException" might be good, but the 'throws' statements need to be granular and well documented.
