### ISSUE TITLE
Inconsistent errors with large amounts

### ISSUE THREAD

**Issue by dominic** [chain/chain#339]
Trying to build an action with amount

```
99999999999999999999
```

results in the following error:

```
Action 1 amount must be an integer.
```

However, attempting to build an action with amount

```
10000000000000000000
```

returns an action-specific error of:

```
amount 10000000000000000000 exceeds maximum value 2^63
```

**Comment by jbowens** [comment]
Values between 2^63 and 2^64 will result in action errors like `amount x exceeds maximum value 2^63`. Values greater than 2^64 will fail when unmarshaling json before we ever hit a handler because they're too big to fit in an integer.

Honestly, not sure if this worth caring about. Once we're using gRPC, client SDKs won't let you create an amount greater than 64 bits.

**Comment by jbowens** [comment]
If we wanted to deal with this, I guess the answer would be to use `math/big.Int` in all of our request structs and convert them to an int within the handler.

**Comment by kr** [comment]
Or maybe use math/big in the error cases so we don't have to pollute the actual data types and common-case execution paths.

**Comment by kr** [comment]
Oh because httpjson doesn't even call the handler. So to do that we'd have to put it in the error handler callback `WriteHTTPError` :/
