### ISSUE TITLE
Dashboard produces "blank check" error when "unbalanced transaction" would be more helpful

### ISSUE THREAD

**Issue by bobg** [chain/chain#340]
Create a transaction in the dashboard with some inputs and no outputs, and try to submit. The error you get is CH705: "Unsafe transaction: leaves assets to be taken without requiring payment." But that error is intended for users of the API, where unbalanced transactions might legitimately need to be created for e.g. atomic swaps. The dashboard deals only in balanced transactions, so "unbalanced transaction" would be a more informative and actionable error message.

**Comment by bobg** [comment]
> The dashboard deals only in balanced transactions

Except when `Advanced Options>Allow additional actions` is selected, but this issue isn't for that case.

**Comment by jeffomatic** [comment]
The dashboard could present a synthetic error (not generated by the API) if CH705 is received and `Allow additional actions` is checked. This would improve usability in the dashboard in a way that arguably should be applied to the SDK as well. The SDK presents confusion in an analogous way, but because the `allow_additional_actions` flag is presented at the sign step, there isn't a logical way to produce the desirable error message at the build step.

However, in service to future features, we have been talking about moving `allow_additional_actions` to the build step. This resolves a lot of things: we could detect unbalanced transactions in the API during the build stage, which in turn means that the dashboard and SDK can both take advantage of better error messages without resorting to handling special cases. Before resolving this specific issue, it would be good to see where this change (a breaking one) will land in the roadmap before we apply the quick fix.
