### ISSUE TITLE
protocol: blockchain.Writer interface to encapsulate serialization flags

### ISSUE THREAD

**Issue by oleganza** [chain/chain#390]
@bobg, I'm looking at this rebase conflict where I added serialization flags and you extracted `WriteExtensibleString` helper. The problem is that `WriteExtensibleString` expects a func that takes only a writer. Adding extra params such as serialization flags feels imprudent.

This makes me think we should have `blockchain.Writer` interface that implements `io.Writer` and has `serializationFlags()` method so we can access them when writing txs and blocks? Not sure we need TxWriter and BlockWriter, but we can add those as "subtypes" of blockchain.Writer with tx- or block-specific functionality if needed later.

WDYT? /cc @kr

 ```
// assumes w has sticky errors
func (t *TxInput) writeTo(w io.Writer, serflags uint8) {
    blockchain.WriteVarint63(w, t.AssetVersion) // TODO(bobg): check and return error
<<<<<<< f0c469ed8fa7e0af92dec7441d42dca5e4199826
    blockchain.WriteExtensibleString(w, t.WriteInputCommitment)
=======
    buf := bufpool.Get()
    defer bufpool.Put(buf)
    t.WriteInputCommitment(buf, serflags)
    blockchain.WriteVarstr31(w, buf.Bytes())
>>>>>>> fixing up outputids and unspentids
    blockchain.WriteVarstr31(w, t.ReferenceData)
    if serflags&SerWitness != 0 {
        blockchain.WriteExtensibleString(w, t.writeInputWitness)
    }
}

<<<<<<< f0c469ed8fa7e0af92dec7441d42dca5e4199826
func (t *TxInput) WriteInputCommitment(w io.Writer) error {
=======
func (t *TxInput) WriteInputCommitment(w io.Writer, serflags uint8) {
>>>>>>> fixing up outputids and unspentids
    if t.AssetVersion == 1 {
        switch inp := t.TypedInput.(type) {
        case *IssuanceInput:
            _, err := w.Write([]byte{0}) // issuance type
            if err != nil {
                return err
            }
            _, err = blockchain.WriteVarstr31(w, inp.Nonce)
            if err != nil {
                return err
            }
            assetID := t.AssetID()
            _, err = w.Write(assetID[:])
            if err != nil {
                return err
            }
            _, err = blockchain.WriteVarint63(w, inp.Amount)
            return err

        case *SpendInput:
<<<<<<< f0c469ed8fa7e0af92dec7441d42dca5e4199826
            _, err := w.Write([]byte{1}) // spend type
            if err != nil {
                return err
            }
            _, err = inp.OutputID.WriteTo(w)
            if err != nil {
                return err
            }
            err = inp.OutputCommitment.writeTo(w, t.AssetVersion)
            return err
=======
            w.Write([]byte{1}) // spend type
            inp.OutputID.WriteTo(w)
            if serflags&SerPrevout != 0 {
                inp.OutputCommitment.writeTo(w, t.AssetVersion)
            } else {
                prevouthash := inp.OutputCommitment.Hash(t.AssetVersion)
                w.Write(prevouthash[:])
            }
>>>>>>> fixing up outputids and unspentids
        }
    }
    return nil
}
```

**Comment by bobg** [comment]
> The problem is that WriteExtensibleString expects a func that takes only a writer. Adding extra params such as serialization flags feels imprudent.

The calls to `WriteExtensibleString` happen typically (exclusively?) in contexts where a `serflags` value is available. The func passed to `WriteExtensibleString` can be a closure whose scope contains that value. So it should be possible to get away without needing to pass `serflags` explicitly to that callback, and indeed that appears to be idiomatic Go style.

But this logic is already in flux, because we've found that the encoding/decoding logic is brittle and can be automated based on the definitions of the data types involved. One partial take at automating this is on the https://github.com/chain/chain/tree/autowriter branch (see [auto.go](https://github.com/chain/chain/blob/autowriter/encoding/blockchain/auto.go)), which uses reflection at runtime to read and write blockchain data structures. Since that code is performance-critical, I've written most of another approach this weekend: a compile-time static code generator, which I intend to finish in the next day or two.

**Comment by oleganza** [comment]
Oh, so for now i can wrap `t.WriteInputCommitment` in a closure that captures the serflags? Will do.
