### ISSUE TITLE
Commitment to UTXO state should not be updated every block?

### ISSUE THREAD

**Issue by oleganza** [chain/chain#413]
We probably should allow block signers to commit UTXO state every some number of blocks. This should give some flexibility in terms of optimizing recalculation process. The nodes would need to keep the diff set of UTXO modifications in-between these commitments.

@kr, I wonder if the patricia trie/set recomputation requires some optimization like that?

**Comment by kr** [comment]
Interesting. This might help if a significant fraction of items in the diff set cancel out, making the total diff smaller than the sum of the sizes of the individual diffs.

Otherwise, it's hard to see how this would buy us anything, since we have to apply all the updates anyway. If we delay some of them until a later block it's still the same amount of work.
