### ISSUE TITLE
make slashland run upload-docs

### ISSUE THREAD

**Issue by kr** [chain/chain#66]
So we continuously deploy our documentation from main.

**Comment by jeffomatic** [comment]
We just wanna be a little careful here that this is what we want to do. It'll make Maven a dependency of the local landing process, and it will mean that we will have to be very careful when merging doc updates to main; I don't know if (up to this point) that merging to main means the same thing as wanting to go live.

Also, there are some peculiarities of the uploaded that we should account for. First, it takes a while. Second, there is actually a nontrivial post-upload step that sets content types on extensionless files. I haven't seen it in person but I believe that during the time window before this step finishes, our doc pages actually download (the S3 default content type is binary octet stream) rather than show up in the browser window. Which means there is essentially a bit of downtime when deploying the docs.

Anyway, just want to double check that this is what we really want.
